# Generated by Django 2.2.13 on 2020-10-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='General'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(default='MultiColor'),
        ),
    ]
