# Generated by Django 3.1.2 on 2020-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201025_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lattitude',
            field=models.DecimalField(decimal_places=14, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=10000),
        ),
    ]
